<div class="page-actions">
    <div class="page-actions-inner">
        <div class="page-actions-buttons">
            <button
                class="action-primary"
                onclick="setLocation('<?php echo $block->getUrl('movie/movie/add') ?>')"
                title="<?php echo __('Add New Movie') ?>">
                <?php echo __('Add New Movie') ?>
            </button>

        </div>
    </div>
</div>