<div class="page-actions">
    <div class="page-actions-inner">
        <div class="page-actions-buttons">

            <button
                class="action-secondary back"
                onclick="setLocation('<?php echo $block->getUrl('movie/movie') ?>')"
                title="<?php echo __('Back') ?>">
                <?php echo __('Back') ?>
            </button>

        </div>
    </div>
</div>